services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: csr_volunteer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./server
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_ADDRESS: ":8080"
      POSTGRES_DB: csr_volunteer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_URL: postgres://postgres:postgres@db:5432/csr_volunteer?sslmode=disable
      CORS_ALLOW_ORIGINS: http://localhost:3000,http://localhost:5500
    ports:
      - "8080:8080"

volumes:
  db-data:

